package ru.elite.core;

public enum GOVERNMENT {
    ANARCHY, COLONY, COMMUNISM, CONFEDERACY, COOPERATIVE, CORPORATE,
    DEMOCRACY, DICTATORSHIP, FEUDAL, IMPERIAL, PATRONAGE, PRISON_COLONY,
    THEOCRACY, NONE, ENGINEER, WORKSHOP
}
